---
title: "RWorksheet_DelaCruz4b"
output: pdf_document
date: "2023-11-08"
---

```{r 1.}
vectorA <- c(1, 2, 3, 4, 5)

zeroMatrix <- matrix(0, nrow = 5, ncol = 5)

for (i in 1:5) {
  zeroMatrix[1, i] <- vectorA[i]
}

zeroMatrix

```

```{r 3.}
calculate_fibonacci <- function(limit) {

  a <- 0
  b <- 1
  
  cat(a, " ")
  cat(b, " ")
  
  repeat {

    next_number <- a + b
    
    if (next_number > limit) {
      break  
    }
    
    cat(next_number, " ")
    
    a <- b
    b <- next_number
  }
}

user_input <- as.numeric(readline("Enter the starting number for the Fibonacci sequence: "))

if (!is.na(user_input) && user_input > 0) {
  calculate_fibonacci(500)
} else {
  cat("Invalid input. Please enter a valid positive number.\n")
}

```

```{r 4.}
library(readxl)
HouseholdData <- read_excel("C:\\Users\\ASUS\\Documents\\Worksheet#4\\Worksheet#4\\HouseholdData.xlsx")
View(HouseholdData)
```

```{r 4. b}
males <-  HouseholdData[HouseholdData$Gender == "M",]
males

females <-  HouseholdData[HouseholdData$Gender == "F",]
females
```

```{r 4. c}
library(ggplot2)
plot(males, main = "Males",)
```