---
title: "Worksheet_#4a"
author: "Kyla Ysabelle De la Cruz"
date: "2023-11-15"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Number 1}
#1. 
library(readxl)
HouseholdData <- read_excel("C:\\Users\\ASUS\\Documents\\Worksheet#4\\Worksheet#4\\HouseholdData.xlsx")
HouseholdData
#1.a. In the data frame, it shows three columns; Shoe size, Height, and Gender along
# with corresponding data within the rows.
```

```{r 1.b}
#1.b

males <-  HouseholdData[HouseholdData$Gender == "M",]
males

females <-  HouseholdData[HouseholdData$Gender == "F",]
females
```

```{r 1.c}
#1.c

colMeans(HouseholdData[c(1, 2)])
# Shoe Size    Height 
#  9.410714 68.571429 
```

```{r 1.d}
#1.d
# Yes, because it the person's height corresponds to their shoe size.
```

```{r 2}
#2.
months_vector <- c("March","April","January","November","January",
            "September","October","September","November","August",
            "January","November","November","February","May","August",
            "July","December","August","August","September","November","February",
            "April")
months_vector

factor_months_vector <- factor(months_vector)
factor_months_vector
```

```{r 3}
#3. 
summary(factor_months_vector)
summary(months_vector)
# Yes, they are both useful in this case since factoring the factor_months_vector shows you the
# amount of times a month had been repeated/stated within the vector.
# While in the months_vector, it shows the length, class, and mode of the variables inside the object.
```

```{r 4}
#4.
factor_data <- c("East", "West", "West", "West", "West", "North","North","North")
new_order_data <- factor(factor_data, levels = c("East","West","North"))
new_order_data 
```

```{r 5}
#5.
excel_read <- read.csv("import_march.csv")
excel_read
```

```{r 6}
#6. 

# number <- 1:50
# user_input <- as.integer(readline(prompt = "Enter a number 1-50: "))
# 
# if (user_input >= 1 && user_input <= 50) {
#   cat(TRUE)
# } else{
#   cat(user_input)
# }

#Turned into comment because it won't knit

```

```{r 7}
minimum_bills <- function(price) {
  bills_type <- c(1000, 500, 200, 100, 50)
  total <- 0
  
  if (price %% 50 == 0) {
    for (bill in bills_type) {
      bill_count <- price %/% bill
      total <- total + bill_count
      price <- price %% bill
    }
    
    cat("Minimum number of bills needed: ", total, "\n")
  } else {
    cat("Price must be divisible by 50\n")
  }
}

snack_price <- 1350  
minimum_bills(snack_price)
```

```{r 7.2}
min_bills <- function(price) {
  bills <- c(500, 200, 100, 50)

  num_bills <- 0


  for (bill in bills) {
    while (price >= bill) {
      price <- price - bill
      
      num_bills <- num_bills + 1
    }
  }

  return(num_bills)
}

price <- sample(1000:5000, size = 1)

num_bills <- min_bills(price)

print(num_bills)
```

```{r 8}
data <- data.frame(
  NAME = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85, 90)
)
data

data$AvgScore <- (data$Grade1 + data$Grade2 + data$Grade3 + data$Grade4) / 4

students_over_90 <- data[data$AvgScore > 90, ]
students_over_90
```

```{r 8A-B}
data <- data.frame(
  NAME = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85, 90)
)
data$AvgMathScore <- (data$Grade1 + data$Grade2 + data$Grade3 + data$Grade4) / 4


Annie_Ave <- data[data$NAME == "Annie", "AvgMathScore"]
paste("Annie's average grade this semester is", Annie_Ave)


Thea_Ave <- data[data$NAME == "Thea", "AvgMathScore"]
paste("Thea's average grade this semester is", Thea_Ave)


Steve_Ave <- data[data$NAME == "Steve", "AvgMathScore"]
paste("Steve's average grade this semester is", Steve_Ave)


Hanna_Ave <- data[data$NAME == "Hanna", "AvgMathScore"]
paste("Hanna's average grade this semester is", Hanna_Ave)
```

```{r 8c}
data <- data.frame(
  NAME = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85, 90)
)

data$AvgScore <- (data$Grade1 + data$Grade2 + data$Grade3 + data$Grade4) / 4

students_below_80 <- data[data$AvgScore < 80, ]
students_below_80
```

```{r 8d}
students <- c("Annie", "Thea", "Steve", "Hanna")

for (student in students) {
  max_score <- max(data[data$NAME == student, 2:5])
  cat(student, "Max Score:", max_score, "\n")
}
```