---
title: "RWorksheet_Delacruz#3b"
output: html_document
date: "2023-10-12"
---

```{r household data frame}
#1.a
household_df <- data.frame(
  Respondents = 1:20,
  Sex = c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,1,2),
  Fathers_Occupation = c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1),
  Persons_at_Home = c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6),
  Siblings_at_School = c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2),
  Types_of_Houses = c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2)
)
household_df
```

```{r 1b}
#1.b The data frame displays the columns with their corresponding column names; Respondents, Sex, Fathers Occupation, Persons at Home, Siblings at School, and Types of Houses.
#There are 20 respondents and they are either male or female, their fathers occupations are either farmer, driver or others. They also state the family size through Persons at Home and Siblings at 
#school (showing who are currently attending and are at home.) Lastly, it displays the type of home
#the respondents have, such as Wood, Semi-Concrete, and Concrete.

#    Respondents Sex Fathers_Occupation Persons_at_Home Siblings_at_School Types_of_Houses
# 1            1   2                  1               5                  6               1
# 2            2   2                  3               7                  4               2
# 3            3   1                  3               3                  4               3
# 4            4   2                  3               8                  1               1
# 5            5   2                  1               5                  2               1
# 6            6   2                  2               9                  1               3
# 7            7   2                  3               6                  5               3
# 8            8   2                  1               7                  3               1
# 9            9   2                  1               8                  1               2
# 10          10   2                  1               4                  2               3
# 11          11   1                  3               7                  3               2
# 12          12   2                  2               5                  2               3
# 13          13   2                  1               4                  5               2
# 14          14   2                  3               7                  5               2
# 15          15   2                  3               8                  2               3
# 16          16   2                  1               8                  1               3
# 17          17   2                  3               3                  2               3
# 18          18   2                  1              11                  5               3
# 19          19   1                  2               7                  3               3
# 20          20   2                  1               6                  2               2
```

```{r mean}
#1.c
mean(household_df$Siblings_at_School)
#The mean number of siblings attending is 2.95
```

```{r 1.d}
#1.d
household_df[1:2,]
#   Respondents Sex Fathers_Occupation Persons_at_Home Siblings_at_School Types_of_Houses
# 1           1   2                  1               5                  6               1
# 2           2   2                  3               7                  4               2
```

```{r 1.e}
#1.e
household_df[c(3,5),c(2,4)]
#   Sex Persons_at_Home
# 3   1               3
# 5   2               5
```

```{r type houses}
#1.f
types_houses <- c(household_df$Types_of_Houses)
types_houses
```

```{r male farmers}
#1.g
male_farmers <- household_df[household_df$Sex == 1 & household_df$Fathers_Occupation == 1,]
male_farmers
# [1] Respondents        Sex                Fathers_Occupation Persons_at_Home    Siblings_at_School Types_of_Houses   
# <0 rows> (or 0-length row.names) There are no male farmers in the data frame.
```

```{r females with siblings greater than 5}
#1.h
female_greater_than_5_siblings <- household_df[household_df$Sex == 2 & household_df$Siblings_at_School >= 5,]
female_greater_than_5_siblings
# Respondents Sex Fathers_Occupation Persons_at_Home Siblings_at_School Types_of_Houses
# 1            1   2                  1               5                  6               1
# 7            7   2                  3               6                  5               3
# 13          13   2                  1               4                  5               2
# 14          14   2                  3               7                  5               2
# 18          18   2                  1              11                  5               3
```

``` {r dataframe}
#2.
df = data.frame(Ints=integer(),
                Doubles=double(), Characters=character(),
                Logicals=logical(),
                Factors=factor(),
                stringsAsFactors=FALSE)
print("Structure of the empty dataframe:")
print(str(df))
#It shows each data type and their corresponding variable types.
```

``` {r household data frame and csv}
#3.
householdData <- data.frame(
  Respondents = 1:10,
  Sex = c("Male", "Female", "Female","Male","Male","Female","Female", "Male", "Female", "Male"),
  Fathers_Occupation = c(1,2,3,3,1,2,2,3,1,3),
  Persons_at_Home = c(5,7,3,8,6,4,4,2,11,6),
  Siblings_at_School = c(2,3,0,5,2,3,1,2,6,2),
  Types_of_Houses = c("Wood", "Congrete", "Congrete", "Wood", "Semi-Congrete", "Semi-Congrete", "Wood", "Semi-Congrete", "Semi-Congrete", "Congrete")
)
householdData
```

```{r household csv}
#3.a
householdCSV <- "HouseholdData.csv"
write.csv(householdData, file = householdCSV, row.names = FALSE)
read.csv("C:\\Users\\ASUS\\Documents\\worksheet#3\\HouseholdData.csv")
```

```{r household conversion: sex}
#3.b
householdData$Sex <-  factor(householdData$Sex, c("Male","Female"),
                             levels(householdData$Sex) <- c(1, 2))
householdData
# Respondents Sex Fathers_Occupation Persons_at_Home Siblings_at_School Types_of_Houses
# 1            1   1                  1               5                  2            Wood
# 2            2   2                  2               7                  3        Congrete
# 3            3   2                  3               3                  0        Congrete
# 4            4   1                  3               8                  5            Wood
# 5            5   1                  1               6                  2   Semi-Congrete
# 6            6   2                  2               4                  3   Semi-Congrete
# 7            7   2                  2               4                  1            Wood
# 8            8   1                  3               2                  2   Semi-Congrete
# 9            9   2                  1              11                  6   Semi-Congrete
# 10          10   1                  3               6                  2        Congrete
```

```{r household conversion: types of house}
#3.c
householdData$Types_of_Houses <- factor(householdData$Types_of_Houses,
                                        levels = c("Wood", "Congrete", "Semi-Congrete"))


levels(householdData$Types_of_Houses) <- c(1, 2, 3)
householdData 

#    Respondents Sex Fathers_Occupation Persons_at_Home Siblings_at_School Types_of_Houses
# 1            1   1                  1               5                  2               1
# 2            2   2                  2               7                  3               2
# 3            3   2                  3               3                  0               2
# 4            4   1                  3               8                  5               1
# 5            5   1                  1               6                  2               3
# 6            6   2                  2               4                  3               3
# 7            7   2                  2               4                  1               1
# 8            8   1                  3               2                  2               3
# 9            9   2                  1              11                  6               3
# 10          10   1                  3               6                  2               2
```

```{r household conversion: fathers occupation}
#3.d
fathersOccupation <- householdData$Fathers_Occupation <- factor(householdData$Fathers_Occupation,
                                                                levels = c(1, 2, 3),
                                                                labels = c("Farmer", "Driver", "Others"))
householdData    

#    Respondents Sex Fathers_Occupation Persons_at_Home Siblings_at_School Types_of_Houses
# 1            1   1             Farmer               5                  2               1
# 2            2   2             Driver               7                  3               2
# 3            3   2             Others               3                  0               2
# 4            4   1             Others               8                  5               1
# 5            5   1             Farmer               6                  2               3
# 6            6   2             Driver               4                  3               3
# 7            7   2             Driver               4                  1               1
# 8            8   1             Others               2                  2               3
# 9            9   2             Farmer              11                  6               3
# 10          10   1             Others               6                  2               2
```

``` {r household conversion: female drivers}
#3.e
female_drivers <- householdData[householdData$Sex == 2 & householdData$Fathers_Occupation == "Driver",]
female_drivers

#   Respondents Sex Fathers_Occupation Persons_at_Home Siblings_at_School Types_of_Houses
# 2           2   2             Driver               7                  3               2
# 6           6   2             Driver               4                  3               3
# 7           7   2             Driver               4                  1               1
```

``` {r more siblings}
#3.f
more_siblings <- householdData[householdData$Siblings_at_School >=5,]
more_siblings

#   Respondents Sex Fathers_Occupation Persons_at_Home Siblings_at_School Types_of_Houses
# 4           4   1             Others               8                  5               1
# 9           9   2             Farmer              11                  6               3
```

```{r analysis}
#4.

# The graph continuously demonstrates that the number of negative sentiments is the highest, 
# followed by that of neutral and positive attitudes. Negative sentiment peaked on July 15, 2020, 
# while positive sentiment peaked on July 21, 2020, and neutral sentiment peaked on July 15, 2020. O
# n July 20, 2020, the sentiments' lowest number was tallied.
```